sudo: false
language: python

git:
  depth: 1

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      env: Python=2.4
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.4
            - python-virtualenv
      before_install: . .travis/setup_virtualenv.sh '2.4'
    - os: linux
      python: '3.2'
    #- os: linux
      #python: '3.6'
    #- os: linux
      #python: pypy3
    - os: linux
      python: "pypy-5.8.0"
    - os: linux
      python: "pypy3-5.8.0"
  allow_failures:
    - os: osx
  fast_finish: true

install:
  #- if [[ $TOXENV == 'py32' || $TOXENV == 'pypy3' ]]; then pip install setuptools==29.0.1; else pip install -U setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.4' ]]; then pip install unittest2; fi
  - .travis/setup_codecov.sh

script:
  - .travis/run_codecov.sh 'pycompatlayer.py'

after_success:
  # Upload result
  - if [[ $TRAVIS_PYTHON_VERSION != '2.4' ]]; then codecov; fi

deploy:
  provider: releases
  api_key: $TEST_TOKEN
  file: LICENSE
  on:
    repo: ale5000-git/test
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
