sudo: false
language: python
python:
  - "2.6"
  - "3.4"
  - "pypy"
matrix:
  include:
    - os: linux
    - os: osx
      language: generic
  allow_failures:
    - os: osx
env:
  - RUN_TYPE=dumb
addons:
  apt:
    packages:
      #- android-tools-adb
      #- p7zip-full
      #- zipalign

install: true

script:
  #- nosetests
  - python test.py
