sudo: false
language: python

matrix:
  include:
    #- os: linux
      #python: "2.6"
    - os: linux
      python: "3.4"
    - os: linux
      python: "pypy"
    - os: osx
      language: generic
  allow_failures:
    - os: osx
env:
  - RUN_TYPE=dumb
addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi

install: true

script:
  #- nosetests
  - python test.py
