sudo: false
language: python

matrix:
  include:
    #- os: linux
      #python: "2.6"
    - os: linux
      python: "3.4"
    - os: linux
      python: "pypy"
    - os: osx
      python: "2.7"
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

env:
  - RUN_TYPE=dumb

#before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi;

install: true

script:
  - python test.py
