sudo: false
language: python

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      python: "2.6"
      env: TOXENV=py26
    - os: linux
      python: "3.2"
    - os: linux
      python: "nightly"
    - os: linux
      python: "pypy"
    - os: linux
      python: "pypy3"
    - os: osx
      language: generic
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

install: true
script: python test.py
