language: android
sudo: false
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - jdk_switcher use oraclejdk8
  - echo sdk.dir $ANDROID_HOME > local.properties
  - export TERM=dumb
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - ./gradlew clean assembleDebug test lint
  - cat "/home/travis/build/ale5000-git/test/build/outputs/lint-results-debug.xml"
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# https://github.com/codecov/example-python/blob/master/.travis.yml

install:
  - pip install codecov

script:
  - coverage run _Old/test.py

after_success:
  - codecov
