sudo: false
language: python

git:
  depth: 1

env:
  global: TERM=dumb

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py-default
  allow_failures:
    - os: osx
  fast_finish: true

install:
  #- if [[ $TOXENV == 'py32' || $TOXENV == 'pypy3' ]]; then pip install setuptools==29.0.1; else pip install -U setuptools; fi
  #- pip install codecov
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi;
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew cask install java; fi;

script:
  #- if [[ $TOXENV != 'py32' ]]; then echo Running Coverage...; coverage run setup.py test; else echo Running script...; python pycompatlayer.py; fi

after_success:
  #- if [[ $TOXENV != 'py32' ]]; then codecov; fi
