sudo: false
language: python
os:
  - linux
  - osx
python:
  - "2.6"
  - "3.4"
  - "pypy"
env:
  - RUN_TYPE=dumb
addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

install: true

script:
  #- nosetests
  - python test.py
