sudo: false
language: python

git:
  depth: 1

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      env: Python='2.4'
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.4
            - python-virtualenv
      before_install:
        - virtualenv ~/virtualenv/python2.4
        - virtualenv -p /usr/bin/python2.4 ~/virtualenv/python2.4
        - cp -pf ~/virtualenv/python2.4/bin/python2.4 ~/virtualenv/python2.4/bin/python
        - source ~/virtualenv/python2.4/bin/activate
        - export TRAVIS_PYTHON_VERSION=2.4
    - os: linux
      python: '3.6'
    - os: linux
      python: pypi3
  allow_failures:
    - os: osx
  fast_finish: true

install:
  #- easy_install pip==1.1
  #- if [[ $TOXENV == 'py32' || $TOXENV == 'pypy3' ]]; then pip install setuptools==29.0.1; else pip install -U setuptools; fi
  #- pip install unittest2
  #- pip install codecov

script:
  - echo $TRAVIS_PYTHON_VERSION
  - python -V
  - pip -V
  - .travis/run_coverage.sh 'pycompatlayer.py'

after_success:
  #- if [[ $TOXENV != 'py32' ]]; then codecov; fi

deploy:
  provider: releases
  api_key: $TEST_TOKEN
  file: LICENSE
  on:
    repo: ale5000-git/test
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
