sudo: false
language: python

git:
  depth: 1

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      language: generic
      env: TOXENV=py24
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages: python2.4
      before_install:
        - python -m venv venv
        - source venv/bin/activate
    - os: linux
      python: "3.6"
      env: TOXENV=py36
  allow_failures:
    - os: osx
  fast_finish: true

install:
  #- if [[ $TOXENV == 'py32' || $TOXENV == 'pypy3' ]]; then pip install setuptools==29.0.1; else pip install -U setuptools; fi
  - pip install unittest2
  - pip install codecov

script:
  - if [[ $TOXENV != 'py32' ]]; then coverage run setup.py test; else echo python setup.py test; fi

after_success:
  #- if [[ $TOXENV != 'py32' ]]; then codecov; fi

deploy:
  provider: releases
  api_key: $TEST_TOKEN
  file: LICENSE
  on:
    repo: ale5000-git/test
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
