sudo: false
language: python

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      python: "2.6"
      env: TOXENV=py26
    - os: linux
      python: "3.2"
      env: TOXENV=py32
    - os: linux
      python: "3.3"
      env: TOXENV=py33
    #- os: linux
      #python: "nightly"
      #env: TOXENV=py-nightly
    #- os: linux
      #python: "pypy"
      #env: TOXENV=pypy
    #- os: linux
      #python: "pypy3"
      #env: TOXENV=pypy3
    - os: linux
      language: android
      android:
        components:
          - android-22
          - sys-img-armeabi-v7a-android-22
      env: TOXENV=android-emu
    #- os: osx
      #language: generic
      #env: TOXENV=py-default
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  apt:
    sources:
      #- android-tools
      #- debian-sid
    packages:
      #- p7zip-full
      #- zipalign
      #- openjdk-6-jre
      #- openjdk-6-jdk
      #- android-tools-adb

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install p7zip; fi

# https://github.com/codecov/example-python/blob/master/.travis.yml

#install: "pip install -r requirements/requirements.pip"
install:
  #- pip install --upgrade pip
  - pip install pycompatlayer
  - pip install codecov

script:
  - python _Old/test.py
  - if [[ $TRAVIS_OS_NAME != 'osx' && $TOXENV == 'py26' ]]; then coverage run _Old/test.py; fi

after_success:
  #- codecov
