sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 2.6
      env: TOXENV=py26
    - os: linux
      python: 3.4
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py34
  allow_failures:
    - os: osx
env:
  - RUN_TYPE=dumb
addons:
  apt:
    packages:
      #- android-tools-adb
      #- p7zip-full
      #- zipalign

install: true

script:
  #- nosetests
  - python test.py
