sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - RUN_TYPE=dumb
addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

before_install:
  #- sudo apt-get -qq update
  - sudo apt-get install -y zipalign
install: true

script:
  - nosetests
  - python test.py
