sudo: false

matrix:
  include:
    - os: linux
      language: python
      python: "2.6"
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "pypy"
    - os: linux
      language: python
      python: "pypy3"
    - os: osx
      language: generic
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

env:
  - RUN_TYPE=dumb

install: true

script:
  - python test.py
