sudo: false
language: python

git:
  depth: 1

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      env: Python=2.4
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.4
            - python2.4-dev
            - python-virtualenv1.7.2
      before_install: . .travis/setup_virtualenv.sh '2.4'
    - os: linux
      env: Python=2.5
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.5
            - python2.5-dev
            - python-virtualenv
      before_install: . .travis/setup_virtualenv.sh '2.5'
    - os: linux
      python: '3.6'
  fast_finish: true

install:
  - .travis/setup_dependencies.sh

script:
  - .travis/run_codecov.sh 'pycompatlayer.py'

after_success:
  # Upload results
  #- if [[ $TRAVIS_PYTHON_VERSION != '2.4' ]]; then codecov; else bash <(curl -s https://codecov.io/bash); fi

#deploy:
  #provider: releases
  #api_key: $TEST_TOKEN
  #file: LICENSE
  #on:
    #repo: ale5000-git/test
    #condition: $TRAVIS_PYTHON_VERSION = "3.6"
