sudo: false
os: linux
language: python

git:
  depth: 1

env:
  global:
    - TERM=dumb
    - SKIP=false

matrix:
  include:
    - env: Python=2.3
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.3
            #- python2.3-dev
            - python-virtualenv
      before_install: . .travis/setup_virtualenv.sh
    - env: Python=2.5
      language: generic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fkrull/deadsnakes'
          packages:
            - python2.5
            - python2.5-dev
            - python-virtualenv=1.7.1.2-1
      before_install: . .travis/setup_virtualenv.sh
    #- python: '3.6'

    - env: Jython=latest
      python: '2.7'
      addons:
        apt:
          packages:
            - jython
      before_install:
        #- easy_install virtualenv==1.9.1
        - unset JYTHON_HOME
        #- virtualenv -p "jython" --setuptools "~/virtualenv/jython"
        #- deactivate
        #- unset JYTHON_HOME
        #- source "~/virtualenv/jython/bin/activate"

    #- os: osx
      #env: Python='default (macOS)'
      #language: generic
  exclude:
    - env: Python=2.3
    - env: Python=2.4
    - env: Python=2.5
    - env: Python=3.1
  allow_failures:
    - os: osx
  fast_finish: true

install:
  #- .travis/setup_dependencies.sh

script:
  - python -V
  #- .travis/run_codecov.sh 'pycompatlayer.py'

after_success:
  # Upload results
  #- if [[ $TRAVIS_PYTHON_VERSION != '2.4' ]]; then codecov; else bash <(curl -s https://codecov.io/bash); fi

#deploy:
  #provider: releases
  #api_key: $TEST_TOKEN
  #file: LICENSE
  #on:
    #repo: ale5000-git/test
    #condition: $TRAVIS_PYTHON_VERSION = "3.6"
