sudo: false
language: python

matrix:
  include:
    #- os: linux
      #python: "2.6"
    - os: linux
      python: "3.4"
    - os: linux
      python: "pypy"
    - os: osx
  allow_failures:
    - os: osx
    - language: generic

addons:
  apt:
    packages:
      #- android-tools-adb
      - p7zip-full
      #- zipalign

env:
  - RUN_TYPE=dumb

install: true

script:
  - python test.py
