sudo: false
language: python

env:
  global: TERM=dumb

matrix:
  include:
    - os: linux
      python: "2.6"
      env: TOXENV=py26
    - os: linux
      python: "3.2"
      env: TOXENV=py32
    - os: linux
      python: "nightly"
      env: TOXENV=py-nightly
    - os: linux
      python: "pypy"
      env: TOXENV=pypy
    - os: linux
      python: "pypy3"
      env: TOXENV=pypy3
    - os: osx
      language: generic
      env: TOXENV=py-default
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  apt:
    packages:
      - p7zip-full
      - openjdk-6-jre
      - openjdk-6-jdk
      #- android-tools-adb
jdk:
  - openjdk6

before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install p7zip; fi

install: true
script: python test.py
